package com.stowflow.inventra.service;

public enum ChatIntent {
    GREETING,
    UNKNOWN,
    FAQ_PROCUREMENT,
    FAQ_HELP,
    LIST_ALERTS,
    DASHBOARD_SUMMARY,
    ORDERS_SUMMARY,
    REPLENISHMENT_SUMMARY,
    ARTICLE_STOCK,
    ARTICLE_SEARCH,
    OPEN_INVENTORY,
    OPEN_ORDERS,
    OPEN_REPLENISHMENT,
    OPEN_SUPPLIERS,
    OPEN_DASHBOARD,
    OPEN_PRODUCTS,
    OPEN_HELP,
    OPEN_POS,
    OPEN_PLATFORM,
    SUGGEST_REPLENISH,
    SUGGEST_ORDER,
    CREATE_REPLENISH
}
